### ISSUE TITLE
Secondary Contact REDCap Administrator

### ISSUE THREAD

**Issue by ghost** [ctsit/modify_contact_admin_button#12]
In version 12.3.1, a new "Contact REDCap administrator" link has been added near the top of the project's left-hand module which provides users a secondary place to contact their REDCap admin. Can this module be modified to replace both links?

![ContactREDCapAdmin](https://user-images.githubusercontent.com/79642848/173083134-7ebc46ad-00cd-427c-acca-93f28727298e.png)

Thank you for considering.

**Comment by pbchase** [comment]
> Can this module be modified to replace both links?

We just upgraded to RC 12.4.2 tonight. Now @tlstoffs wants the same thing. :-)  We'll look into it.

**Comment by jangari** [comment]
Hi @pbchase, I submitted PR #13 for this. Didn't realise this issue was here. Was responding to Yelena's community post.

**Comment by pbchase** [comment]
> Hi @pbchase, I submitted PR #13 for this. Didn't realise this issue was here. Was responding to Yelena's community post.

Many thanks for the PR. I've asked @ChemiKyle to take a look today if he has time.

**Comment by ChemiKyle** [comment]
Closed by #13

**Comment by jangari** [comment]
As noted in the community thread, this fix won't work in all cases as it uses the customisable anchor text. I'm submitting another PR (#16) to change strategies and use the fa-envelope icon and get its sibling anchor node. Ugly, but more reliable.
